spring.application.name=otp-service
server.port=5503

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8000/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

