package com.orion.organization_service.dto;

import com.fasterxml.jackson.annotation.JsonAlias;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ProjectRequest {

    /**
     * Project code — REQUIRED for UPDATE and lookups.
     * NOT used or accepted during CREATE (auto-generated by service).
     */
    @JsonAlias({"projectCode", "project_code"})
    private String code;

    /** Project name — REQUIRED for CREATE, optional for UPDATE. */
    private String name;

    /** Optional short description (max 100 chars). */
    private String description;
}
